[2024-10-27T19:52:42.870+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: holiday_etl_pipeline.process_metrics scheduled__2024-10-26T00:00:00+00:00 [queued]>
[2024-10-27T19:52:42.884+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: holiday_etl_pipeline.process_metrics scheduled__2024-10-26T00:00:00+00:00 [queued]>
[2024-10-27T19:52:42.885+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-27T19:52:42.899+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_metrics> on 2024-10-26 00:00:00+00:00
[2024-10-27T19:52:42.905+0000] {standard_task_runner.py:60} INFO - Started process 658 to run task
[2024-10-27T19:52:42.907+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'holiday_etl_pipeline', 'process_metrics', 'scheduled__2024-10-26T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/holidays_orchestror.py', '--cfg-path', '/tmp/tmpu5ywkwjy']
[2024-10-27T19:52:42.909+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask process_metrics
[2024-10-27T19:52:42.950+0000] {task_command.py:423} INFO - Running <TaskInstance: holiday_etl_pipeline.process_metrics scheduled__2024-10-26T00:00:00+00:00 [running]> on host 09302ea91fa9
[2024-10-27T19:52:43.031+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='holiday_etl_pipeline' AIRFLOW_CTX_TASK_ID='process_metrics' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-26T00:00:00+00:00'
[2024-10-27T19:52:43.032+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/holidays_orchestror.py", line 82, in consolidate_metrics
    "total_records": landing_result["metrics"]["total_records"],
                     ~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-10-27T19:52:43.040+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=holiday_etl_pipeline, task_id=process_metrics, execution_date=20241026T000000, start_date=20241027T195242, end_date=20241027T195243
[2024-10-27T19:52:43.051+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 26 for task process_metrics ('NoneType' object is not subscriptable; 658)
[2024-10-27T19:52:43.080+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-27T19:52:43.093+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-27T20:26:19.186+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: holiday_etl_pipeline.process_metrics scheduled__2024-10-26T00:00:00+00:00 [queued]>
[2024-10-27T20:26:19.193+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: holiday_etl_pipeline.process_metrics scheduled__2024-10-26T00:00:00+00:00 [queued]>
[2024-10-27T20:26:19.194+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-27T20:26:19.208+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_metrics> on 2024-10-26 00:00:00+00:00
[2024-10-27T20:26:19.214+0000] {standard_task_runner.py:60} INFO - Started process 238 to run task
[2024-10-27T20:26:19.216+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'holiday_etl_pipeline', 'process_metrics', 'scheduled__2024-10-26T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/holidays_orchestror.py', '--cfg-path', '/tmp/tmpm12ibktc']
[2024-10-27T20:26:19.219+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask process_metrics
[2024-10-27T20:26:19.256+0000] {task_command.py:423} INFO - Running <TaskInstance: holiday_etl_pipeline.process_metrics scheduled__2024-10-26T00:00:00+00:00 [running]> on host be01200d7c31
[2024-10-27T20:26:19.341+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='holiday_etl_pipeline' AIRFLOW_CTX_TASK_ID='process_metrics' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-26T00:00:00+00:00'
[2024-10-27T20:26:19.342+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/holidays_orchestror.py", line 82, in consolidate_metrics
    "total_records": landing_result["metrics"]["total_records"],
                     ~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-10-27T20:26:19.351+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=holiday_etl_pipeline, task_id=process_metrics, execution_date=20241026T000000, start_date=20241027T202619, end_date=20241027T202619
[2024-10-27T20:26:19.361+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task process_metrics ('NoneType' object is not subscriptable; 238)
[2024-10-27T20:26:19.389+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-27T20:26:19.416+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-27T20:31:09.782+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: holiday_etl_pipeline.process_metrics scheduled__2024-10-26T00:00:00+00:00 [queued]>
[2024-10-27T20:31:09.788+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: holiday_etl_pipeline.process_metrics scheduled__2024-10-26T00:00:00+00:00 [queued]>
[2024-10-27T20:31:09.788+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-27T20:31:09.798+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_metrics> on 2024-10-26 00:00:00+00:00
[2024-10-27T20:31:09.802+0000] {standard_task_runner.py:60} INFO - Started process 218 to run task
[2024-10-27T20:31:09.804+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'holiday_etl_pipeline', 'process_metrics', 'scheduled__2024-10-26T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/holidays_orchestror.py', '--cfg-path', '/tmp/tmp14wogtv9']
[2024-10-27T20:31:09.806+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask process_metrics
[2024-10-27T20:31:09.843+0000] {task_command.py:423} INFO - Running <TaskInstance: holiday_etl_pipeline.process_metrics scheduled__2024-10-26T00:00:00+00:00 [running]> on host 85554215aad0
[2024-10-27T20:31:09.921+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='holiday_etl_pipeline' AIRFLOW_CTX_TASK_ID='process_metrics' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-26T00:00:00+00:00'
[2024-10-27T20:31:09.922+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/holidays_orchestror.py", line 82, in consolidate_metrics
    "total_records": landing_result["metrics"]["total_records"],
                     ~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-10-27T20:31:09.931+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=holiday_etl_pipeline, task_id=process_metrics, execution_date=20241026T000000, start_date=20241027T203109, end_date=20241027T203109
[2024-10-27T20:31:09.939+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task process_metrics ('NoneType' object is not subscriptable; 218)
[2024-10-27T20:31:09.977+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-27T20:31:09.989+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-27T21:14:42.752+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: holiday_etl_pipeline.process_metrics scheduled__2024-10-26T00:00:00+00:00 [queued]>
[2024-10-27T21:14:42.758+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: holiday_etl_pipeline.process_metrics scheduled__2024-10-26T00:00:00+00:00 [queued]>
[2024-10-27T21:14:42.759+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-27T21:14:42.768+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_metrics> on 2024-10-26 00:00:00+00:00
[2024-10-27T21:14:42.773+0000] {standard_task_runner.py:60} INFO - Started process 245 to run task
[2024-10-27T21:14:42.775+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'holiday_etl_pipeline', 'process_metrics', 'scheduled__2024-10-26T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/holidays_orchestror.py', '--cfg-path', '/tmp/tmpj26_bzyr']
[2024-10-27T21:14:42.777+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask process_metrics
[2024-10-27T21:14:42.808+0000] {task_command.py:423} INFO - Running <TaskInstance: holiday_etl_pipeline.process_metrics scheduled__2024-10-26T00:00:00+00:00 [running]> on host f28df99dfa84
[2024-10-27T21:14:42.880+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='holiday_etl_pipeline' AIRFLOW_CTX_TASK_ID='process_metrics' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-26T00:00:00+00:00'
[2024-10-27T21:14:42.881+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/holidays_orchestror.py", line 82, in consolidate_metrics
    "total_records": landing_result["metrics"]["total_records"],
                     ~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-10-27T21:14:42.889+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=holiday_etl_pipeline, task_id=process_metrics, execution_date=20241026T000000, start_date=20241027T211442, end_date=20241027T211442
[2024-10-27T21:14:42.897+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 21 for task process_metrics ('NoneType' object is not subscriptable; 245)
[2024-10-27T21:14:42.908+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-27T21:14:42.920+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
