[2024-10-27T20:05:31.036+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: holiday_etl_pipeline.extract_to_landing manual__2024-10-27T19:47:07.556749+00:00 [queued]>
[2024-10-27T20:05:31.041+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: holiday_etl_pipeline.extract_to_landing manual__2024-10-27T19:47:07.556749+00:00 [queued]>
[2024-10-27T20:05:31.042+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 4
[2024-10-27T20:05:31.050+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): extract_to_landing> on 2024-10-27 19:47:07.556749+00:00
[2024-10-27T20:05:31.054+0000] {standard_task_runner.py:60} INFO - Started process 346 to run task
[2024-10-27T20:05:31.056+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'holiday_etl_pipeline', 'extract_to_landing', 'manual__2024-10-27T19:47:07.556749+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/holidays_orchestror.py', '--cfg-path', '/tmp/tmpen6havq2']
[2024-10-27T20:05:31.058+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask extract_to_landing
[2024-10-27T20:05:31.090+0000] {task_command.py:423} INFO - Running <TaskInstance: holiday_etl_pipeline.extract_to_landing manual__2024-10-27T19:47:07.556749+00:00 [running]> on host e5369d4b74ff
[2024-10-27T20:05:31.141+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='holiday_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_to_landing' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T19:47:07.556749+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-27T19:47:07.556749+00:00'
[2024-10-27T20:05:34.821+0000] {logging_mixin.py:188} INFO - Erro na extração dos feriados: [Errno 2] No such file or directory: 's3a://datalake/datalake/landing/holidays/year=2024/holidays_2024-10-27.json'
[2024-10-27T20:05:35.128+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/scripts/landing/holliday_landing.py", line 218, in extract_to_landing
    self._save_to_json(all_holidays, file_path)
  File "/opt/airflow/dags/scripts/landing/holliday_landing.py", line 178, in _save_to_json
    with open(file_path, 'w', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 's3a://datalake/datalake/landing/holidays/year=2024/holidays_2024-10-27.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/holidays_orchestror.py", line 39, in extract_holidays
    return HolidayLandingOrchestrator.extract_holidays()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/landing/holliday_landing.py", line 255, in extract_holidays
    result = extractor.extract_to_landing()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/landing/holliday_landing.py", line 238, in extract_to_landing
    raise Exception(error_msg)
Exception: Erro na extração dos feriados: [Errno 2] No such file or directory: 's3a://datalake/datalake/landing/holidays/year=2024/holidays_2024-10-27.json'
[2024-10-27T20:05:35.138+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=holiday_etl_pipeline, task_id=extract_to_landing, execution_date=20241027T194707, start_date=20241027T200531, end_date=20241027T200535
[2024-10-27T20:05:35.148+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task extract_to_landing (Erro na extração dos feriados: [Errno 2] No such file or directory: 's3a://datalake/datalake/landing/holidays/year=2024/holidays_2024-10-27.json'; 346)
[2024-10-27T20:05:35.161+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-27T20:05:35.181+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
