[2024-10-27T20:37:05.694+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: holiday_etl_pipeline.process_metrics manual__2024-10-27T20:30:56.364990+00:00 [queued]>
[2024-10-27T20:37:05.700+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: holiday_etl_pipeline.process_metrics manual__2024-10-27T20:30:56.364990+00:00 [queued]>
[2024-10-27T20:37:05.700+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-27T20:37:05.709+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_metrics> on 2024-10-27 20:30:56.364990+00:00
[2024-10-27T20:37:05.713+0000] {standard_task_runner.py:60} INFO - Started process 510 to run task
[2024-10-27T20:37:05.715+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'holiday_etl_pipeline', 'process_metrics', 'manual__2024-10-27T20:30:56.364990+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/holidays_orchestror.py', '--cfg-path', '/tmp/tmpoqn4hhr6']
[2024-10-27T20:37:05.717+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask process_metrics
[2024-10-27T20:37:05.745+0000] {task_command.py:423} INFO - Running <TaskInstance: holiday_etl_pipeline.process_metrics manual__2024-10-27T20:30:56.364990+00:00 [running]> on host 85554215aad0
[2024-10-27T20:37:05.810+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='holiday_etl_pipeline' AIRFLOW_CTX_TASK_ID='process_metrics' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T20:30:56.364990+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-27T20:30:56.364990+00:00'
[2024-10-27T20:37:05.812+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/holidays_orchestror.py", line 82, in consolidate_metrics
    "total_records": landing_result["metrics"]["total_records"],
                     ~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-10-27T20:37:05.819+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=holiday_etl_pipeline, task_id=process_metrics, execution_date=20241027T203056, start_date=20241027T203705, end_date=20241027T203705
[2024-10-27T20:37:05.828+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task process_metrics ('NoneType' object is not subscriptable; 510)
[2024-10-27T20:37:05.847+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-27T20:37:05.859+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
