[2024-10-27T20:10:39.690+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: holiday_etl_pipeline.process_metrics manual__2024-10-27T19:47:07.556749+00:00 [queued]>
[2024-10-27T20:10:39.696+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: holiday_etl_pipeline.process_metrics manual__2024-10-27T19:47:07.556749+00:00 [queued]>
[2024-10-27T20:10:39.697+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 4
[2024-10-27T20:10:39.706+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_metrics> on 2024-10-27 19:47:07.556749+00:00
[2024-10-27T20:10:39.710+0000] {standard_task_runner.py:60} INFO - Started process 587 to run task
[2024-10-27T20:10:39.712+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'holiday_etl_pipeline', 'process_metrics', 'manual__2024-10-27T19:47:07.556749+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/holidays_orchestror.py', '--cfg-path', '/tmp/tmp8omsy_zw']
[2024-10-27T20:10:39.714+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask process_metrics
[2024-10-27T20:10:39.747+0000] {task_command.py:423} INFO - Running <TaskInstance: holiday_etl_pipeline.process_metrics manual__2024-10-27T19:47:07.556749+00:00 [running]> on host e5369d4b74ff
[2024-10-27T20:10:39.830+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='holiday_etl_pipeline' AIRFLOW_CTX_TASK_ID='process_metrics' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T19:47:07.556749+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-27T19:47:07.556749+00:00'
[2024-10-27T20:10:39.832+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/holidays_orchestror.py", line 82, in consolidate_metrics
    "total_records": landing_result["metrics"]["total_records"],
                     ~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-10-27T20:10:39.841+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=holiday_etl_pipeline, task_id=process_metrics, execution_date=20241027T194707, start_date=20241027T201039, end_date=20241027T201039
[2024-10-27T20:10:39.849+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task process_metrics ('NoneType' object is not subscriptable; 587)
[2024-10-27T20:10:39.884+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-27T20:10:39.897+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
